### ISSUE TITLE
[Assignment #1][Q2][SVM] 모듈 임포트 오류..?

### ISSUE THREAD

**Issue by chaeoneee** [okaybody10/CS231n_study#3]
** 스터디장 멘션할 필요 없습니다 **

# 막힌 문제 번호

# 막힌 파일명
SVM

# 막힌 부분
![image](https://user-images.githubusercontent.com/110464678/215720394-478f7293-53d0-495f-b9a6-82027feef4b7.png)

todo 부분에 대한 질문은 아닌데 
위 캡처에서 analytic 값이 다 0으로 나오는데 이게 뭐 때문인지를 모르겠습니다..
그리고 코드 실행은 다 되는데 모듈 임포트 해올 때 노란 밑줄 오류가 떠서 이것 때문인가 싶습니다..
해결해보려고 이것 저것 해봤는데 해결이 안되네요ㅜ 간단한 오류 같은데 해결 방법을 모르겠어서 질문 드립니다..!!!

**Comment by okaybody10** [comment]
CS231n 폴더내에 gradient.check 파일이 있나요?

**Comment by okaybody10** [comment]
아 그리고 numerical은 계산을 제대로 해주고있고, analytic이 채원님께서 짜신 코드를 바탕으로 계산을 해주는 도구에요. 

아마 `svm_naive`를 다시 확인해보시는게 좋을것 같네요. 이쪽에서 값을 전혀 뿜어내고 있지 않아요

**Comment by chaeoneee** [comment]
네넵 확인해보겠습니다 감사합니다!
